Config:
  data_model_version: 1.2.0
  temp_folder: tmp
  backup_folder: /tmp/data-loader-backups

  neo4j:
    # Location of Neo4j server, e.g., bolt://127.0.0.1:7687
    uri: bolt://ip_address:7687
    # Neo4j username
    user: neo4j
    # Neo4j password
    password: password

  # Schema files' locations
  schema:
    - config/ccdi-model.yml
    - config/ccdi-model-props.yml

  plugins:
    - module: loader_plugins.visit_creator
      class: VisitCreator
    - module: loader_plugins.individual_creator
      class: IndividualCreator

  #Property file location
  prop_file: config/props-ccdi-model.yml

  # Skip validations, aka. Cheat Mode
  cheat_mode: false
  # Validations only, skip loading
  dry_run: false
  # Wipe out database before loading, you'll lose all data!
  wipe_db: true
  # Skip backup step
  no_backup: false
  # Automatically confirm deletion and database wiping (without asking user to confirm)
  no_confirmation: false
  # Max violations to display, default is 10, false means ignore
  max_violations: false

  # S3 bucket name, if you are loading from an S3 bucket
  s3_bucket: ccdi-nonprod-inventory-etl-staging-update
  # S3 folder for dataset
  s3_folder: test
  # S3 bucket name for depositing log files
  s3_bucket_logs: ccdi-nonprod-inventory-etl-error-messages
  # S3 folder for depositing log files
  s3_folder_logs: test
  # S3 bucket name for failed data files
  s3_bucket_fail: ccdi-nonprod-inventory-etl-outcome-failure
  # S3 folder name for failed data files
  s3_folder_fail: test
  # S3 bucket name for successful data files
  s3_bucket_success: ccdi-nonprod-inventory-etl-outcome-success
  # S3 folder name for successful data files
  s3_folder_success: test
  # Loading mode, can be UPSERT_MODE, NEW_MODE or DELETE_MODE, default is UPSERT_MODE
  loading_mode: UPSERT_MODE
  # Location of dataset
  dataset: data
