Properties:
  domain: ccdi.cancer.gov
  rel_prop_delimiter: "$"

  plurals:
    cell_line: cell_lines
    clinical_measure_file: clinical_measure_files
    diagnosis: diagnosises
    exposure: exposures
    family_relationship: family_relationships
    follow_up: follow_ups
    medical_history: medical_historys
    molecular_test: molecular_tests
    methylation_array_file: methylation_array_files
    participant: participants
    pathology_file: pathology_files
    pdx: pdxs
    publication: publications
    radiology_file: radiology_files
    sample: samples
    single_cell_sequencing_file: single_cell_sequencing_files
    sequencing_file: sequencing_files
    study: studies
    study_admin: study_admins
    study_arm: study_arms
    study_funding: study_fundings
    study_personnel: study_personnels
    synonym: synonyms
    therapeutic_procedure: therapeutic_procedures

  type_mapping:
    string: String
    number: Float
    integer: Int
    boolean: Boolean
    array: Array
    object: Object
    datetime: DateTime
    date: Date
    TBD: String

  id_fields:
    tmp: id