Properties:
  domain: cds.cancer.gov
  rel_prop_delimiter: "$"

  plurals:
    study: studies
    study_admin: study_admins
    participant: participants
    diagnosis: diagnoses
    treatment: treatments
    specimen: specimens
    sample: samples
    file: files
    genomic_info: genomic_info


  type_mapping:
    string: String
    number: Float
    integer: Int
    boolean: Boolean
    array: Array
    object: Object
    datetime: DateTime
    date: Date
    TBD: String

  id_fields:
    clinical_measure_file: clinical_measure_file_id
    diagnosis: diagnosis_id
    exposure: exposure_id
    family_relationship: family_relationship_id
    follow_up: follow_up_id
    medical_history: medical_history_id
    molecular_test: molecular_test_id
    methylation_array_file: methylation_array_file_id
    participant: participant_id
    pathology_file: pathology_file_id
    pdx: pdx_id
    publication: publication_id
    radiology_file: radiology_file_id
    sample: sample_id
    single_cell_sequencing_file: single_cell_sequencing_file_id
    sequencing_file: sequencing_file_id
    study: study_id
    study_admin: study_admin_id
    study_arm: study_arm_id
    study_funding: study_funding_id
    study_personnel: study_personnel_id
    synonym: synonym_id
    therapeutic_procedure: therapeutic_procedure_id 
